Switch to better monorepo structure (#1)
Using yarn workspaces instead.

Solves the TODO item:
```
Remove "skipLibCheck": true from lk-demo-client. Workaround for error TS2300: Duplicate identifier 'RTCDataChannelState'. From symlinked node_modules + ts-loader interactions.
```